[2024-10-10T04:30:36.599+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-10T04:30:36.631+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_behaviour.dbt_run scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-10T04:30:36.649+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_behaviour.dbt_run scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-10T04:30:36.650+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-10T04:30:36.677+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-10-09 00:00:00+00:00
[2024-10-10T04:30:36.684+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=121) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-10T04:30:36.687+0000] {standard_task_runner.py:63} INFO - Started process 129 to run task
[2024-10-10T04:30:36.687+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_run', 'scheduled__2024-10-09T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmpm_zkh2zl']
[2024-10-10T04:30:36.689+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask dbt_run
[2024-10-10T04:30:36.761+0000] {task_command.py:426} INFO - Running <TaskInstance: user_behaviour.dbt_run scheduled__2024-10-09T00:00:00+00:00 [running]> on host 10fc3afc5804
[2024-10-10T04:30:36.871+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_behaviour' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-09T00:00:00+00:00'
[2024-10-10T04:30:36.872+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-10T04:30:36.893+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-10T04:30:36.894+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-10T04:30:36.907+0000] {subprocess.py:86} INFO - Output:
[2024-10-10T04:30:40.578+0000] {subprocess.py:93} INFO - [0m04:30:40  Running with dbt=1.8.7
[2024-10-10T04:30:41.927+0000] {subprocess.py:93} INFO - [0m04:30:41  Registered adapter: snowflake=1.8.3
[2024-10-10T04:30:42.111+0000] {subprocess.py:93} INFO - [0m04:30:42  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-10T04:30:42.111+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-10-10T04:30:42.112+0000] {subprocess.py:93} INFO - - models.data_pipeline.marts
[2024-10-10T04:30:42.300+0000] {subprocess.py:93} INFO - [0m04:30:42  Found 2 models, 3 data tests, 2 sources, 454 macros
[2024-10-10T04:30:42.303+0000] {subprocess.py:93} INFO - [0m04:30:42
[2024-10-10T04:30:44.338+0000] {subprocess.py:93} INFO - [0m04:30:44  Concurrency: 10 threads (target='dev')
[2024-10-10T04:30:44.339+0000] {subprocess.py:93} INFO - [0m04:30:44
[2024-10-10T04:30:44.357+0000] {subprocess.py:93} INFO - [0m04:30:44  1 of 1 START sql view model dbt_schema.stg_tpch_orders ......................... [RUN]
[2024-10-10T04:30:45.253+0000] {subprocess.py:93} INFO - [0m04:30:45  1 of 1 OK created sql view model dbt_schema.stg_tpch_orders .................... [[32mSUCCESS 1[0m in 0.89s]
[2024-10-10T04:30:45.258+0000] {subprocess.py:93} INFO - [0m04:30:45
[2024-10-10T04:30:45.259+0000] {subprocess.py:93} INFO - [0m04:30:45  Finished running 1 view model in 0 hours 0 minutes and 2.95 seconds (2.95s).
[2024-10-10T04:30:45.301+0000] {subprocess.py:93} INFO - [0m04:30:45
[2024-10-10T04:30:45.301+0000] {subprocess.py:93} INFO - [0m04:30:45  [32mCompleted successfully[0m
[2024-10-10T04:30:45.302+0000] {subprocess.py:93} INFO - [0m04:30:45
[2024-10-10T04:30:45.303+0000] {subprocess.py:93} INFO - [0m04:30:45  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-10-10T04:30:46.685+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-10T04:30:46.686+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-10T04:30:46.712+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=user_behaviour, task_id=dbt_run, run_id=scheduled__2024-10-09T00:00:00+00:00, execution_date=20241009T000000, start_date=20241010T043036, end_date=20241010T043046
[2024-10-10T04:30:46.741+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-10T04:30:46.760+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-10T04:30:46.763+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-11T13:57:36.246+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-11T13:57:36.278+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_behaviour.dbt_run scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-11T13:57:36.291+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_behaviour.dbt_run scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-11T13:57:36.292+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-11T13:57:36.312+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-10-09 00:00:00+00:00
[2024-10-11T13:57:36.324+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=398) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-11T13:57:36.326+0000] {standard_task_runner.py:63} INFO - Started process 412 to run task
[2024-10-11T13:57:36.326+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_run', 'scheduled__2024-10-09T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmpf9rpl9ur']
[2024-10-11T13:57:36.331+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask dbt_run
[2024-10-11T13:57:36.408+0000] {task_command.py:426} INFO - Running <TaskInstance: user_behaviour.dbt_run scheduled__2024-10-09T00:00:00+00:00 [running]> on host 7326b1a9492c
[2024-10-11T13:57:36.562+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_behaviour' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-09T00:00:00+00:00'
[2024-10-11T13:57:36.565+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-11T13:57:36.605+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-11T13:57:36.607+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-11T13:57:36.627+0000] {subprocess.py:86} INFO - Output:
[2024-10-11T13:57:40.340+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2024-10-11T13:57:40.341+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2024-10-11T13:57:40.341+0000] {subprocess.py:93} INFO - 
[2024-10-11T13:57:40.341+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/opt/***/dbt/data_pipeline/profiles/' does not exist.
[2024-10-11T13:57:40.638+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-10-11T13:57:40.639+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-11T13:57:40.652+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-10-11T13:57:40.659+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=user_behaviour, task_id=dbt_run, run_id=scheduled__2024-10-09T00:00:00+00:00, execution_date=20241009T000000, start_date=20241011T135736, end_date=20241011T135740
[2024-10-11T13:57:40.675+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 412)
[2024-10-11T13:57:40.714+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-11T13:57:40.735+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-11T13:57:40.738+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
