[2024-10-10T04:30:51.987+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-10T04:30:52.018+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_behaviour.dbt_test manual__2024-10-10T04:30:22.137535+00:00 [queued]>
[2024-10-10T04:30:52.036+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_behaviour.dbt_test manual__2024-10-10T04:30:22.137535+00:00 [queued]>
[2024-10-10T04:30:52.037+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-10T04:30:52.053+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-10-10 04:30:22.137535+00:00
[2024-10-10T04:30:52.061+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-10T04:30:52.064+0000] {standard_task_runner.py:63} INFO - Started process 170 to run task
[2024-10-10T04:30:52.064+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_test', 'manual__2024-10-10T04:30:22.137535+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmpcxbr49nt']
[2024-10-10T04:30:52.065+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask dbt_test
[2024-10-10T04:30:52.117+0000] {task_command.py:426} INFO - Running <TaskInstance: user_behaviour.dbt_test manual__2024-10-10T04:30:22.137535+00:00 [running]> on host 10fc3afc5804
[2024-10-10T04:30:52.234+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_behaviour' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-10-10T04:30:22.137535+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-10T04:30:22.137535+00:00'
[2024-10-10T04:30:52.235+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-10T04:30:52.250+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-10T04:30:52.251+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt test --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-10T04:30:52.262+0000] {subprocess.py:86} INFO - Output:
[2024-10-10T04:30:55.187+0000] {subprocess.py:93} INFO - [0m04:30:55  Running with dbt=1.8.7
[2024-10-10T04:30:56.423+0000] {subprocess.py:93} INFO - [0m04:30:56  Registered adapter: snowflake=1.8.3
[2024-10-10T04:30:56.587+0000] {subprocess.py:93} INFO - [0m04:30:56  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-10T04:30:56.588+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-10-10T04:30:56.588+0000] {subprocess.py:93} INFO - - models.data_pipeline.marts
[2024-10-10T04:30:56.781+0000] {subprocess.py:93} INFO - [0m04:30:56  Found 2 models, 3 data tests, 2 sources, 454 macros
[2024-10-10T04:30:56.784+0000] {subprocess.py:93} INFO - [0m04:30:56
[2024-10-10T04:30:57.800+0000] {subprocess.py:93} INFO - [0m04:30:57  Concurrency: 10 threads (target='dev')
[2024-10-10T04:30:57.801+0000] {subprocess.py:93} INFO - [0m04:30:57
[2024-10-10T04:30:57.824+0000] {subprocess.py:93} INFO - [0m04:30:57  1 of 3 START test source_not_null_tpch_orders_o_orderkey ....................... [RUN]
[2024-10-10T04:30:57.826+0000] {subprocess.py:93} INFO - [0m04:30:57  2 of 3 START test source_relationships_tpch_lineitem_l_orderkey__o_orderkey__source_tpch_orders_  [RUN]
[2024-10-10T04:30:57.827+0000] {subprocess.py:93} INFO - [0m04:30:57  3 of 3 START test source_unique_tpch_orders_o_orderkey ......................... [RUN]
[2024-10-10T04:30:58.764+0000] {subprocess.py:93} INFO - [0m04:30:58  1 of 3 PASS source_not_null_tpch_orders_o_orderkey ............................. [[32mPASS[0m in 0.94s]
[2024-10-10T04:30:58.839+0000] {subprocess.py:93} INFO - [0m04:30:58  2 of 3 PASS source_relationships_tpch_lineitem_l_orderkey__o_orderkey__source_tpch_orders_  [[32mPASS[0m in 1.01s]
[2024-10-10T04:30:58.928+0000] {subprocess.py:93} INFO - [0m04:30:58  3 of 3 PASS source_unique_tpch_orders_o_orderkey ............................... [[32mPASS[0m in 1.10s]
[2024-10-10T04:30:58.935+0000] {subprocess.py:93} INFO - [0m04:30:58
[2024-10-10T04:30:58.936+0000] {subprocess.py:93} INFO - [0m04:30:58  Finished running 3 data tests in 0 hours 0 minutes and 2.15 seconds (2.15s).
[2024-10-10T04:30:58.979+0000] {subprocess.py:93} INFO - [0m04:30:58
[2024-10-10T04:30:58.980+0000] {subprocess.py:93} INFO - [0m04:30:58  [32mCompleted successfully[0m
[2024-10-10T04:30:58.980+0000] {subprocess.py:93} INFO - [0m04:30:58
[2024-10-10T04:30:58.981+0000] {subprocess.py:93} INFO - [0m04:30:58  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2024-10-10T04:31:00.334+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-10T04:31:00.335+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-10T04:31:00.360+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=user_behaviour, task_id=dbt_test, run_id=manual__2024-10-10T04:30:22.137535+00:00, execution_date=20241010T043022, start_date=20241010T043052, end_date=20241010T043100
[2024-10-10T04:31:00.410+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-10T04:31:00.445+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-10T04:31:00.448+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
