[2024-10-10T04:30:25.811+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-10T04:30:25.841+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_behaviour.dbt_test scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-10T04:30:25.858+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_behaviour.dbt_test scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-10T04:30:25.858+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-10T04:30:25.880+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-10-09 00:00:00+00:00
[2024-10-10T04:30:25.888+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-10T04:30:25.890+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_test', 'scheduled__2024-10-09T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmpe0mjb4mx']
[2024-10-10T04:30:25.891+0000] {standard_task_runner.py:63} INFO - Started process 91 to run task
[2024-10-10T04:30:25.891+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask dbt_test
[2024-10-10T04:30:25.963+0000] {task_command.py:426} INFO - Running <TaskInstance: user_behaviour.dbt_test scheduled__2024-10-09T00:00:00+00:00 [running]> on host 10fc3afc5804
[2024-10-10T04:30:26.083+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_behaviour' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-09T00:00:00+00:00'
[2024-10-10T04:30:26.084+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-10T04:30:26.111+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-10T04:30:26.113+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt test --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-10T04:30:26.128+0000] {subprocess.py:86} INFO - Output:
[2024-10-10T04:30:29.462+0000] {subprocess.py:93} INFO - [0m04:30:29  Running with dbt=1.8.7
[2024-10-10T04:30:32.048+0000] {subprocess.py:93} INFO - [0m04:30:32  Registered adapter: snowflake=1.8.3
[2024-10-10T04:30:32.254+0000] {subprocess.py:93} INFO - [0m04:30:32  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-10-10T04:30:32.255+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-10-10T04:30:32.255+0000] {subprocess.py:93} INFO - - models.data_pipeline.marts
[2024-10-10T04:30:32.465+0000] {subprocess.py:93} INFO - [0m04:30:32  Found 2 models, 3 data tests, 2 sources, 454 macros
[2024-10-10T04:30:32.468+0000] {subprocess.py:93} INFO - [0m04:30:32
[2024-10-10T04:30:32.429+0000] {subprocess.py:93} INFO - [0m04:30:32  Concurrency: 10 threads (target='dev')
[2024-10-10T04:30:32.429+0000] {subprocess.py:93} INFO - [0m04:30:32
[2024-10-10T04:30:32.445+0000] {subprocess.py:93} INFO - [0m04:30:32  1 of 3 START test source_not_null_tpch_orders_o_orderkey ....................... [RUN]
[2024-10-10T04:30:32.447+0000] {subprocess.py:93} INFO - [0m04:30:32  2 of 3 START test source_relationships_tpch_lineitem_l_orderkey__o_orderkey__source_tpch_orders_  [RUN]
[2024-10-10T04:30:32.449+0000] {subprocess.py:93} INFO - [0m04:30:32  3 of 3 START test source_unique_tpch_orders_o_orderkey ......................... [RUN]
[2024-10-10T04:30:33.279+0000] {subprocess.py:93} INFO - [0m04:30:33  2 of 3 PASS source_relationships_tpch_lineitem_l_orderkey__o_orderkey__source_tpch_orders_  [[32mPASS[0m in 0.83s]
[2024-10-10T04:30:33.714+0000] {subprocess.py:93} INFO - [0m04:30:33  1 of 3 PASS source_not_null_tpch_orders_o_orderkey ............................. [[32mPASS[0m in 1.27s]
[2024-10-10T04:30:33.887+0000] {subprocess.py:93} INFO - [0m04:30:33  3 of 3 PASS source_unique_tpch_orders_o_orderkey ............................... [[32mPASS[0m in 1.43s]
[2024-10-10T04:30:33.893+0000] {subprocess.py:93} INFO - [0m04:30:33
[2024-10-10T04:30:33.894+0000] {subprocess.py:93} INFO - [0m04:30:33  Finished running 3 data tests in 0 hours 0 minutes and 1.42 seconds (1.42s).
[2024-10-10T04:30:33.937+0000] {subprocess.py:93} INFO - [0m04:30:33
[2024-10-10T04:30:33.938+0000] {subprocess.py:93} INFO - [0m04:30:33  [32mCompleted successfully[0m
[2024-10-10T04:30:33.938+0000] {subprocess.py:93} INFO - [0m04:30:33
[2024-10-10T04:30:33.939+0000] {subprocess.py:93} INFO - [0m04:30:33  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2024-10-10T04:30:35.521+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-10T04:30:35.521+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-10T04:30:35.557+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=user_behaviour, task_id=dbt_test, run_id=scheduled__2024-10-09T00:00:00+00:00, execution_date=20241009T000000, start_date=20241010T043025, end_date=20241010T043035
[2024-10-10T04:30:35.954+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-10T04:30:35.982+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-10T04:30:35.985+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-10-11T13:57:36.261+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-11T13:57:36.291+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_behaviour.dbt_test scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-11T13:57:36.306+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_behaviour.dbt_test scheduled__2024-10-09T00:00:00+00:00 [queued]>
[2024-10-11T13:57:36.307+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-11T13:57:36.330+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-10-09 00:00:00+00:00
[2024-10-11T13:57:36.340+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=397) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-11T13:57:36.343+0000] {standard_task_runner.py:63} INFO - Started process 414 to run task
[2024-10-11T13:57:36.342+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_behaviour', 'dbt_test', 'scheduled__2024-10-09T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/user_behaviour.py', '--cfg-path', '/tmp/tmpbz06plh_']
[2024-10-11T13:57:36.352+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask dbt_test
[2024-10-11T13:57:36.421+0000] {task_command.py:426} INFO - Running <TaskInstance: user_behaviour.dbt_test scheduled__2024-10-09T00:00:00+00:00 [running]> on host 7326b1a9492c
[2024-10-11T13:57:36.573+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_behaviour' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-10-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-09T00:00:00+00:00'
[2024-10-11T13:57:36.575+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-11T13:57:36.604+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-11T13:57:36.606+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt test --project-dir /opt/***/dbt/data_pipeline --profiles-dir /opt/***/dbt/data_pipeline/profiles/']
[2024-10-11T13:57:36.628+0000] {subprocess.py:86} INFO - Output:
[2024-10-11T13:57:40.342+0000] {subprocess.py:93} INFO - Usage: dbt test [OPTIONS]
[2024-10-11T13:57:40.343+0000] {subprocess.py:93} INFO - Try 'dbt test -h' for help.
[2024-10-11T13:57:40.343+0000] {subprocess.py:93} INFO - 
[2024-10-11T13:57:40.343+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/opt/***/dbt/data_pipeline/profiles/' does not exist.
[2024-10-11T13:57:40.638+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-10-11T13:57:40.639+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-11T13:57:40.653+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-10-11T13:57:40.659+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=user_behaviour, task_id=dbt_test, run_id=scheduled__2024-10-09T00:00:00+00:00, execution_date=20241009T000000, start_date=20241011T135736, end_date=20241011T135740
[2024-10-11T13:57:40.686+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task dbt_test (Bash command failed. The command returned a non-zero exit code 2.; 414)
[2024-10-11T13:57:40.725+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-11T13:57:40.737+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
